name: Building the project and SonarCloud code analysis

on:
  pull_request:
    branches: ["main", "development"]

jobs:
  sonarcloud-analysis-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          QUARKUS_DEV_DATABASE_KIND: ${{ secrets.QUARKUS_DEV_DATABASE_KIND }}
          QUARKUS_DEV_USER: ${{ secrets.QUARKUS_DEV_USER }}
          QUARKUS_DEV_DATABASE_PASSWORD: ${{ secrets.QUARKUS_DEV_DATABASE_PASSWORD }}
          QUARKUS_DEV_DATABASE_URL: ${{ secrets.QUARKUS_DEV_DATABASE_URL }}
        run:  ./gradlew build jacocoTestReport sonar --info
